name: Dependabot update addon
on: pull_request

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    outputs:
      addon: ${{ steps.addon.outputs.slug }}
      new-version: ${{ steps.metadata.outputs.new-version }}
      package-ecosystem: ${{ steps.metadata.outputs.package-ecosystem }}
    steps:
      - uses: actions/checkout@v4
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - id: addon
        if: ${{ steps.metadata.outputs.directory != '/' }}
        run: |
          cd .${{ steps.metadata.outputs.directory }}
          test -f config.json || exit
          jq -r '"slug=\(.slug)"' config.json >> "$GITHUB_OUTPUT"

  update:
    needs: dependabot
    if: ${{ needs.dependabot.outputs.addon }}
    uses: ./.github/workflows/update.yml
    with:
      addon: ${{ needs.dependabot.outputs.addon }}
      version: ${{ needs.dependabot.outputs.new-version }}
      ref: ${{ github.head_ref }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
